### ISSUE TITLE
bot spinning with automerge label

### ISSUE THREAD

**Issue by iritkatriel** [python/miss-islington#431]
I (a triager) tried to put the automerge label on an approved typo-fix PR, and the bot got stuck in a loop adding and removing the label:  https://github.com/python/cpython/pull/24199

**Comment by Mariatta** [comment]
Thanks for flagging. I've deployed a temporary hotfix, but I think something is weird from GitHub API's side. I will investigate further later on.

**Comment by AlexWaygood** [comment]
This just happened to me, as well, in similar circumstances, in https://github.com/python/cpython/pull/30958:

- The PR was approved by a core dev, and the automerge label had been added by a core dev, but miss-islington failed to merge the PR because all PRs were temporarily blocked due to multiple buildbot failures (https://mail.python.org/archives/list/python-dev@python.org/thread/HU2LH5MX44QZXZ36YS4SOG4ZUPT4E7QT/).
- Once the buildbot failures were resolved and PRs to `main` were no longer blocked, I (a triager) tried removing and re-adding the "automerge" label, thinking I could save core devs some bother and get miss-islington to merge the PR.
- miss-islington then proceeded to remove and re-add the "automerge" label at a rate of about once a second until @ambv came to my aid and figured out how to get her to stop.

**Comment by zware** [comment]
@Mariatta's fix from #521 has been tested on python/cpython#29724 and worked great, so I'm closing the issue.
